### PR TITLE
Resolve Error: Timed out connecting to dotnet

### PR DESCRIPTION
**Pull request by scott-brady**
This PR resolves the "Failed to start gauge API: Timed out connecting to dotnet" intermittent error described in #196. 

It also resolves build warning NETSDK1179 during compilation of the target project.

Additionally it includes some minor doco updates to the README.

### CODE REVIEW

**Review by sriv — APPROVED** [review]

**Comment by sriv** [comment]
Thank you for the fix @scott-brady. Appreciate the cleanup in the README as well.

**Comment by scott-brady** [comment]
Thanks @sriv . Could you please let me know what I need to do to include this in a release? I don't think I have permission to run deployments.

**Comment by sriv** [comment]
Apologies for the delay @scott-brady , ideally I should have tagged this PR as a release candidate and that should have got a build out on merge. 

I have triggered a release, gauge-dotnet 0.5.2 should now be available

**Comment by scott-brady** [comment]
Perfect thanks @sriv 👍

**Pull request merged**
