### PR TITLE
Concept start end notify runner

### PR DESCRIPTION
**Pull request by PiotrNestor**
@sriv 
Handle concept messages
Concept hooks support

### CODE REVIEW

**Comment by PiotrNestor** [comment]
@sriv
Corrected the failing ShouldMapStepDetails test

**Comment by PiotrNestor** [comment]
@sriv
There are issues with the 'Gauge.Dotnet.IntegrationTests'. Not clear to me ...

**Comment by sriv** [comment]
Yes, I could see the problem. I will look into it, but will need some time since I am away presently. My guess is that the cause could be because the seed projects in `_testdata` use older Gauge.CSharp.Lib and these seed projects are used in the integration tests.

**Comment by PiotrNestor** [comment]
@sriv 
In the _testdata sample projects:
- added Concept hooks
- updates gauge_bin/Gauge.CSharp.Lib.dll in gauge_bin

Now the integration test work for me
Passed!  - Failed:     0, Passed:    28, Skipped:     0, Total:    28,

**Comment by sriv** [comment]
the _testdata projects are not full gauge projects, they just have enough for the integration tests. The `gauge run` command will throw errors, but we can ignore that since we are interested in getting the project built more than invoking gauge. Looks like the builds are passing now, fingers crossed...

**Comment by sriv** [comment]
Finally, managed to get the tests and the template updated and the build went green. 

Thank you for your patience @PiotrNestor and the contribution. I believe all the changes for this feature are now merged. Please tag me if you need me to look at anything. thanks!

**Pull request merged**
