### PR TITLE
Add .NET 7 support

### PR DESCRIPTION
**Pull request by mpekurny**
Adding .NET 7.0 support and removing .NET Core 3.1 support since 3.1 is no longer under support by Microsoft.

This is my fist contribution to anything on GitHub, so let me know if something isn't correct with how I did this, thanks.

### CODE REVIEW

**Comment by zabil** [comment]
@mpekurny can you sign the DCO?

**Comment by mpekurny** [comment]
I'm not sure I did that right? I have a verified commit, but it kept the old (unverified) commit?

**Comment by zabil** [comment]
You'll need to modify all the commit message to have the sign-off line. This is different from verifying a commit

https://stackoverflow.com/questions/1962094/what-is-the-sign-off-feature-in-git-for#:~:text=Sign%2Doff%20is%20a%20line,did%20what%2C%20especially%20with%20patches.&text=It%20should%20contain%20the%20user,for%20an%20open%2Dsource%20project.

**Comment by mpekurny** [comment]
@zabil Is this correct? Both have the sign-off line now.

**Pull request merged**
