### PR TITLE
Add .NET 8 support

### PR DESCRIPTION
**Pull request by mpekurny**
Adding .NET 8 support for builds and updated dependencies to latest versions.

### CODE REVIEW

**Comment by mpekurny** [comment]
@sriv @zabil 
I am not really sure why the tests are failing. It looks like it's failing on talking to the html reporting plugin which should not have been impacted from my changes to the dotnet plugin? Also the windows tests were stopped while downloading files, so is there some sort of storage cap we are running into where things are failing because of disk space?

**Comment by sriv** [comment]
It does look a bit strange to start with. I will investigate this

**Comment by sriv** [comment]
thanks @mpekurny !

**Comment by mpekurny** [comment]
@sriv  is the plan to release my changes with the changes in [this PR](https://github.com/getgauge/gauge-dotnet/pull/201)? Any idea when it will be released?

**Comment by mpekurny** [comment]
@sriv  is the plan to release my changes with the changes in [this PR](https://github.com/getgauge/gauge-dotnet/pull/201)? Any idea when it will be released?

**Comment by sriv** [comment]
My apologies. I should have marked this as a release candidate and that would have triggered a release.

I will aim to make a release by this weekend, hope that is acceptable to you?

**Comment by mpekurny** [comment]
Yes, that works. Thanks @sriv

**Comment by sriv** [comment]
gauge-dotnet 0.5.3 is now released, thanks @mpekurny

**Pull request merged**
