### PR TITLE
Add .Net 6 and ARM support

### PR DESCRIPTION
**Pull request by jeremyosterhoudt**
- Added .Net 6.0 support
- Added the ability to build for architectures other than Intel/AMD (Apple Silicon included)

### CODE REVIEW

**Comment by sriv** [comment]
hi @jeremyosterhoudt Thank you for sending this PR, I am taking a look at the changeset. Please note that the commits need to be all signed-off in order for the Developer Certificate of Origin check to pass. You can see the details here: https://github.com/getgauge/gauge-dotnet/pull/174/checks?check_run_id=4734983252

**Comment by jeremyosterhoudt** [comment]
Thanks @sriv.  I've signed the commit.  I did have a question on whether to keep .Net 5 as a target?  My initial feeling is it goes out of service support in March so must people should be migrating to .Net 6 for LTS.  However, laggards won't be able to upgrade to this version who are sticking with .Net 5 targets.

I'm happy to add a 3rd target so .Net 5 and 6 will be targets if needed, but figured I would go with this simpler solution to start.

**Comment by sriv** [comment]
the check for LSP tests are failing, I'll get this sorted

**Comment by sriv** [comment]
The github actions workflow needs some love, the versions used are a bit dated. Feel free to play with it @jeremyosterhoudt if you have the time. It'll probably take me at least a couple of days to  be able to get to it .

**Pull request merged**
