### PR TITLE
Programmatic skip scenario

### PR DESCRIPTION
**Pull request by PiotrNestor**
According to the discussion in: https://github.com/getgauge/gauge/pull/2502

### CODE REVIEW

**Comment by PiotrNestor** [comment]
@sriv 
Go version 1.22 update on Linux issues ...

**Comment by PiotrNestor** [comment]
@sriv 
Also I'll be adding a small update to align with the latest merged gauge-proto

**Comment by PiotrNestor** [comment]
@sriv
Any progress on this PR?

**Comment by sriv** [comment]
i will need to make some time to debug this.

**Comment by PiotrNestor** [comment]
@sriv 
This PR is updated with the latest master updates
The Linux build have problem with --> go: download go1.22 for linux/amd64: toolchain not available

**Comment by sriv** [comment]
@PiotrNestor - I made some changes to the GH actions workflow, could you please rebase this PR?

**Comment by PiotrNestor** [comment]
@sriv
I've missed the rebase request. Now it's done

**Comment by sriv** [comment]
looks like I missed the `setup-go` changes for lsp tests. Would you be able to add 

```
      - name: Setup go
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: false
```
to the LSP tests flow @PiotrNestor ?

**Pull request merged**
